### NumPy


In [8]:
import numpy as np

#### 创建ndarray

In [2]:
# 一维数组
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
# 二维数组
arr2 = np.array([[1,2,3,4],[3,4,5,6]])
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [6]:
arr3 = np.array([1,2,3,4],ndmin=2)
arr3

array([[1, 2, 3, 4]])

In [7]:
### 矢量化
a = [[1,2,3],[2,3,4],[4,5,6]]
b = [[5,2,4],[2,4,5],[5,6,7]]
a,b

([[1, 2, 3], [2, 3, 4], [4, 5, 6]], [[5, 2, 4], [2, 4, 5], [5, 6, 7]])

In [8]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [9]:
a[0][0]

1

In [10]:
c = [[0,0,0],[0,0,0],[0,0,0]]
for i in range(3):
    for j in range(3):
        c[i][j] = a[i][j]*b[i][j]

c

[[5, 4, 12], [4, 12, 20], [20, 30, 42]]

In [11]:
a1 = np.array(a)
b1 = np.array(b)

In [13]:
a1

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [14]:
b1

array([[5, 2, 4],
       [2, 4, 5],
       [5, 6, 7]])

In [15]:
a1*b1

array([[ 5,  4, 12],
       [ 4, 12, 20],
       [20, 30, 42]])

In [16]:
a1+b1

array([[ 6,  4,  7],
       [ 4,  7,  9],
       [ 9, 11, 13]])

In [17]:
a1/b1

array([[0.2       , 1.        , 0.75      ],
       [1.        , 0.75      , 0.8       ],
       [0.8       , 0.83333333, 0.85714286]])

In [18]:
a1*3

array([[ 3,  6,  9],
       [ 6,  9, 12],
       [12, 15, 18]])

In [19]:
a1**3

array([[  1,   8,  27],
       [  8,  27,  64],
       [ 64, 125, 216]], dtype=int32)

### 数据类型

In [20]:
a = np.array([3.14,4,1,2])
a

array([3.14, 4.  , 1.  , 2.  ])

In [21]:
a.dtype

dtype('float64')

In [22]:
a =  np.array([3.14,4,1,2],dtype='int32')

In [24]:
a.dtype

dtype('int32')

In [25]:
a.astype('float32')

array([3., 4., 1., 2.], dtype=float32)

In [29]:
a.astype(np.int64).dtype

dtype('int64')

In [30]:
a.astype('str')

array(['3', '4', '1', '2'], dtype='<U11')

### 常用数组

1.全0数组

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((3,2,4),dtype=np.int64)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)

2. 全1数组

In [35]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.ones([2,3,4],dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

3. 相同值的数组

In [39]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [43]:
np.full((2,3),[[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

4.单位矩阵

In [44]:
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [47]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [48]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.eye(5,k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

5.初始化的数组

In [58]:
a = np.empty([2,3])

In [59]:
a.fill(5.5)

In [60]:
a

array([[5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5]])

In [61]:
a.fill([[1,2,3],[4,5,6]])

ValueError: Input object to FillWithScalar is not a scalar

6.创建对角矩阵

In [62]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [63]:
np.diag([1,2,3,4.5])

array([[1. , 0. , 0. , 0. ],
       [0. , 2. , 0. , 0. ],
       [0. , 0. , 3. , 0. ],
       [0. , 0. , 0. , 4.5]])

In [64]:
np.diag([1,2,3,'a'],2)

array([['', '', '1', '', '', ''],
       ['', '', '', '2', '', ''],
       ['', '', '', '', '3', ''],
       ['', '', '', '', '', 'a'],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U11')

In [65]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

7. 设置空值

In [69]:
np.nan * np.nan

nan

In [67]:
np.nan?

8. 随机数组

In [73]:
np.random.randint(1,10,(3,6)) # 整数

array([[5, 3, 9, 3, 8, 8],
       [2, 8, 8, 2, 9, 9],
       [9, 2, 5, 8, 2, 5]])

In [74]:
np.random.randn(4,5) # 标准正态分布

array([[-0.59077159, -0.48128146, -0.5943284 ,  1.1855561 ,  1.03697299],
       [-0.59757416, -1.99962866,  1.33135279,  0.52335309,  0.8756677 ],
       [ 0.12488771, -0.76952123,  0.64176003, -0.79913439,  0.53964449],
       [-1.21128757, -0.19556325,  0.31039427, -1.31477962,  1.40109631]])

In [75]:
np.random.standard_normal((4,2))

array([[-0.78712633, -0.25603711],
       [ 0.40546951,  0.20994332],
       [ 0.6580015 , -0.03205598],
       [ 0.35160091,  1.93438793]])

In [76]:
np.random.normal(5,2,(5,3)) # 正态分布数组

array([[5.67944401, 7.65357648, 4.5791622 ],
       [4.28422331, 7.99849019, 7.12015196],
       [4.4594455 , 5.92965247, 5.14395486],
       [5.60899949, 3.89610772, 5.71261184],
       [4.44886516, 5.930047  , 6.14559419]])

In [77]:
np.random.random((2,3)) # 返回[0，1]之间数

array([[0.38040654, 0.82324461, 0.78476942],
       [0.81798312, 0.07886694, 0.67126786]])

In [5]:
# 设置随机数种子
np.random.seed(100)
np.random.randn(2,3)

array([[-1.74976547,  0.3426804 ,  1.1530358 ],
       [-0.25243604,  0.98132079,  0.51421884]])

9.线性序列数组

In [4]:
np.arange(0,16,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [84]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [86]:
np.linspace(1,101,5,dtype='int',endpoint=False)

array([ 1, 21, 41, 61, 81])

In [6]:
np.linspace(1,101,5,dtype='int')

array([  1,  26,  51,  76, 101])

In [88]:
np.linspace(1,101,5,retstep=True)

(array([  1.,  26.,  51.,  76., 101.]), 25.0)

### 数组属性

In [89]:
np.random.seed(123)
x1 = np.random.randint(10,size=6) # 一维数组
x2 = np.random.randint(10,size=(3,4)) # 二维数组
x3 = np.random.randint(10,size=(3,4,5)) # 三维数组

In [91]:
x1

array([2, 2, 6, 1, 3, 9])

In [92]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [93]:
x3

array([[[4, 1, 7, 3, 2],
        [4, 7, 2, 4, 8],
        [0, 7, 9, 3, 4],
        [6, 1, 5, 6, 2]],

       [[1, 8, 3, 5, 0],
        [2, 6, 2, 4, 4],
        [6, 3, 0, 6, 4],
        [7, 6, 7, 1, 5]],

       [[7, 9, 2, 4, 8],
        [1, 2, 1, 1, 3],
        [5, 9, 0, 8, 1],
        [6, 3, 3, 5, 9]]])

In [94]:
x1.shape

(6,)

In [95]:
x2.shape

(3, 4)

In [96]:
x3.shape

(3, 4, 5)

In [97]:
x1.dtype

dtype('int32')

In [98]:
x2.dtype

dtype('int32')

In [99]:
x3.dtype

dtype('int32')

In [100]:
x1.ndim

1

In [101]:
x2.ndim

2

In [102]:
x3.ndim

3

In [103]:
x1.size

6

In [104]:
x2.size

12

In [105]:
x3.size

60

In [106]:
x1.itemsize

4

In [107]:
x2.itemsize

4

In [108]:
x3.itemsize

4

In [109]:
x = np.array([1,2,3,4],dtype=np.int8)
x.itemsize

1

### 数组转换

In [110]:
m = np.random.randint(1,100,(2,3,4))
m

array([[[99,  4, 12,  4],
        [95,  7, 10, 88],
        [15, 84, 71, 13]],

       [[55, 28, 39, 18],
        [62, 75, 66, 48],
        [17,  6, 87, 47]]])

In [116]:
m = m.reshape(6,4)

In [117]:
m

array([[99,  4, 12,  4],
       [95,  7, 10, 88],
       [15, 84, 71, 13],
       [55, 28, 39, 18],
       [62, 75, 66, 48],
       [17,  6, 87, 47]])

In [118]:
m.shape

(6, 4)

In [119]:
m.resize(2,3,4)

In [121]:
m.resize(6,4)

In [122]:
m.swapaxes(1,0)

array([[99, 95, 15, 55, 62, 17],
       [ 4,  7, 84, 28, 75,  6],
       [12, 10, 71, 39, 66, 87],
       [ 4, 88, 13, 18, 48, 47]])

In [124]:
m.flatten()

array([99,  4, 12,  4, 95,  7, 10, 88, 15, 84, 71, 13, 55, 28, 39, 18, 62,
       75, 66, 48, 17,  6, 87, 47])

In [125]:
m.reshape(1,-1)

array([[99,  4, 12,  4, 95,  7, 10, 88, 15, 84, 71, 13, 55, 28, 39, 18,
        62, 75, 66, 48, 17,  6, 87, 47]])

In [127]:
m.reshape(-1,1)

array([[99],
       [ 4],
       [12],
       [ 4],
       [95],
       [ 7],
       [10],
       [88],
       [15],
       [84],
       [71],
       [13],
       [55],
       [28],
       [39],
       [18],
       [62],
       [75],
       [66],
       [48],
       [17],
       [ 6],
       [87],
       [47]])

In [128]:
m

array([[99,  4, 12,  4],
       [95,  7, 10, 88],
       [15, 84, 71, 13],
       [55, 28, 39, 18],
       [62, 75, 66, 48],
       [17,  6, 87, 47]])

In [131]:
m = m.astype(np.float32)

In [132]:
m

array([[99.,  4., 12.,  4.],
       [95.,  7., 10., 88.],
       [15., 84., 71., 13.],
       [55., 28., 39., 18.],
       [62., 75., 66., 48.],
       [17.,  6., 87., 47.]], dtype=float32)

In [133]:
m.dtype

dtype('float32')

In [135]:
type(m.tolist())

list

### 索引和切片

In [136]:
arr = np.arange(10)

In [137]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
arr[2]

2

In [139]:
arr[:2]

array([0, 1])

In [140]:
arr[2:8:2]

array([2, 4, 6])

In [141]:
arr[4:7]=888

In [142]:
arr

array([  0,   1,   2,   3, 888, 888, 888,   7,   8,   9])

In [143]:
arr2 = arr[4:8]
arr2

array([888, 888, 888,   7])

In [144]:
arr3 = arr[4:8].copy()
arr3

array([888, 888, 888,   7])

In [145]:
arr3[:]=11

In [146]:
arr3

array([11, 11, 11, 11])

#### 多维数组索引

In [147]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [148]:
arr2d[1]

array([4, 5, 6])

In [149]:
arr2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [151]:
arr2d[0][2]

3

In [152]:
arr2d[0,2]

3

In [153]:
arr2d[:,0]

array([1, 4, 7])

In [154]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [155]:
arr3d = np.arange(1,13).reshape((2,2,3))
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [156]:
arr3d[1,0,2]

9

#### 整数索引

In [157]:
x = np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

(0,0),(1,1),(2,0)

In [159]:
x[np.ix_([0,1,2],
         [0,1,0])]

array([[1, 2, 1],
       [3, 4, 3],
       [5, 6, 5]])

In [160]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [162]:
x[[[0,0],[3,3]],[[0,2],[0,2]]]

array([[ 0,  2],
       [ 9, 11]])

In [164]:
x[[0]]

array([[0, 1, 2]])

In [165]:
x[[0],[0]]

array([0])

In [166]:
x[[0,1],[0,1]]

array([0, 4])

In [168]:
x[[0,0],[0,2]]

array([0, 2])

In [171]:
x[[[0,0],[3,3]],
  [[0,2],[0,2]]]

array([[ 0,  2],
       [ 9, 11]])

In [173]:
x[[[1,2],[2,3]],
  [[0,2],[0,2]]]

array([[ 3,  8],
       [ 6, 11]])

### 布尔索引

In [174]:
x = np.arange(12).reshape(4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [175]:
x>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [176]:
x[x>5]

array([ 6,  7,  8,  9, 10, 11])

In [177]:
a = np.array([np.nan,1,2,np.nan,3,4,5])
a

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [178]:
np.isnan(a)

array([ True, False, False,  True, False, False, False])

In [179]:
a[np.isnan(a)]

array([nan, nan])

In [180]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [ ]:
& | ~

In [182]:
x[(x>5) & (x<7)]

array([6])

In [186]:
x[(x>7) | (x>5)]

array([ 6,  7,  8,  9, 10, 11])

### 数组的切分和组合

### 组合

In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])

In [189]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


In [190]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])

In [191]:
np.hstack((a,b))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])

In [192]:
np.row_stack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])

In [194]:
np.column_stack((a,b))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])

In [197]:
np.concatenate((a,b),axis=1)

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14]])

In [11]:
np.concatenate((a,b),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [11, 12],
       [13, 14]])

#### 切分

In [198]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [199]:
np.hsplit(a,2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19]]), array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23]])]

In [204]:
for i in np.hsplit(a,4):
    print(i)
    print('*'*20)

[[ 0  1]
 [ 8  9]
 [16 17]]
********************
[[ 2  3]
 [10 11]
 [18 19]]
********************
[[ 4  5]
 [12 13]
 [20 21]]
********************
[[ 6  7]
 [14 15]
 [22 23]]
********************


In [206]:
for i in np.vsplit(a,3):
    print(i)
    print('*'*20)

[[0 1 2 3 4 5 6 7]]
********************
[[ 8  9 10 11 12 13 14 15]]
********************
[[16 17 18 19 20 21 22 23]]
********************


In [209]:
for i in np.array_split(a,3,axis=1):
    print(i)
    print('*'*20)

[[ 0  1  2]
 [ 8  9 10]
 [16 17 18]]
********************
[[ 3  4  5]
 [11 12 13]
 [19 20 21]]
********************
[[ 6  7]
 [14 15]
 [22 23]]
********************


### 广播

In [210]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [211]:
a+a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [212]:
b = np.arange(3).reshape(1,3)
b

array([[0, 1, 2]])

In [213]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [214]:
c = np.arange(6).reshape(3,2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [216]:
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [217]:
d = np.arange(3).reshape(3,1)
d

array([[0],
       [1],
       [2]])

In [219]:
b+d

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [220]:
a*3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [221]:
b**2

array([[0, 1, 4]], dtype=int32)

### 数学函数

In [222]:
a = np.arange(9,dtype="float64").reshape(3,3)
b = np.array([10,11,12])
a,b

(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]), array([10, 11, 12]))

In [225]:
np.add(a,b)

array([[10., 12., 14.],
       [13., 15., 17.],
       [16., 18., 20.]])

In [226]:
a+b

array([[10., 12., 14.],
       [13., 15., 17.],
       [16., 18., 20.]])

In [227]:
np.subtract(a,b)

array([[-10., -10., -10.],
       [ -7.,  -7.,  -7.],
       [ -4.,  -4.,  -4.]])

In [228]:
np.subtract(b,a)

array([[10., 10., 10.],
       [ 7.,  7.,  7.],
       [ 4.,  4.,  4.]])

In [229]:
np.multiply(a,b) # 位乘法

array([[ 0., 11., 24.],
       [30., 44., 60.],
       [60., 77., 96.]])

In [230]:
a*b

array([[ 0., 11., 24.],
       [30., 44., 60.],
       [60., 77., 96.]])

In [231]:
np.divide(a,b)

array([[0.        , 0.09090909, 0.16666667],
       [0.3       , 0.36363636, 0.41666667],
       [0.6       , 0.63636364, 0.66666667]])

In [232]:
b/a

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[        inf, 11.        ,  6.        ],
       [ 3.33333333,  2.75      ,  2.4       ],
       [ 1.66666667,  1.57142857,  1.5       ]])

In [237]:
try:
    x = int(input('请输入一个数：'))
    y = int(input('输入除数：'))
    print(x/y)
except (ZeroDivisionError,ValueError) as e:
    print('你的错误信息是',e)

请输入一个数：sd
你的错误信息是 invalid literal for int() with base 10: 'sd'


In [240]:
try:
    x = int(input('请输入一个数：'))
    y = int(input('输入除数：'))
    print(x/y)
except ZeroDivisionError as e:
    print('你的错误信息是',e)

请输入一个数：sd


ValueError: invalid literal for int() with base 10: 'sd'

In [241]:
np.power(b,3)

array([1000, 1331, 1728], dtype=int32)

In [242]:
np.power(3,b)

array([ 59049, 177147, 531441], dtype=int32)

In [243]:
np.mod(a,b)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [249]:
# numpy around
a = np.array([1.0,5.55,123,0.567,25.252])
a

array([  1.   ,   5.55 , 123.   ,   0.567,  25.252])

In [245]:
np.around(a)

array([  1.,   6., 123.,   1.,  25.])

In [250]:
np.around(a,decimals=1)

array([  1. ,   5.6, 123. ,   0.6,  25.3])

In [247]:
np.around(a,decimals=-1)

array([  0.,  10., 120.,   0.,  30.])

In [248]:
np.around(2.5)#四舍六入

2.0

In [253]:
round(4.5)

4

In [255]:
a = np.array([-1.7,1.5,-0.2,10])
a

array([-1.7,  1.5, -0.2, 10. ])

In [256]:
np.floor(a)

array([-2.,  1., -1., 10.])

In [257]:
np.ceil(a)

array([-1.,  2., -0., 10.])

### 字符串函数

In [258]:
a = np.array([['Hello'],['Hi']])
a

array([['Hello'],
       ['Hi']], dtype='<U5')

In [259]:
b = np.array([['abc'],['xyz']])
b

array([['abc'],
       ['xyz']], dtype='<U3')

In [261]:
np.char.add(a,b)

array([['Helloabc'],
       ['Hixyz']], dtype='<U8')

In [262]:
np.char.add(a,'haha')

array([['Hellohaha'],
       ['Hihaha']], dtype='<U9')

In [263]:
np.char.multiply('Hello',3)

array('HelloHelloHello', dtype='<U15')

In [264]:
np.char.multiply(a,3)

array([['HelloHelloHello'],
       ['HiHiHi']], dtype='<U15')

In [268]:
np.char.center("hello",20,fillchar="*")

array('*******hello********', dtype='<U20')

In [269]:
e = np.array(['hello world','how are you'])
np.char.capitalize(e)

array(['Hello world', 'How are you'], dtype='<U11')

In [270]:
np.char.title(e)

array(['Hello World', 'How Are You'], dtype='<U11')

In [273]:
e1 = np.char.upper(e)

In [274]:
e1

array(['HELLO WORLD', 'HOW ARE YOU'], dtype='<U11')

In [275]:
np.char.lower(e1)

array(['hello world', 'how are you'], dtype='<U11')

In [276]:
np.char.split(e)

array([list(['hello', 'world']), list(['how', 'are', 'you'])],
      dtype=object)

In [277]:
np.char.split('Hello,world,how,are,you',sep=',')

array(list(['Hello', 'world', 'how', 'are', 'you']), dtype=object)

In [278]:
np.char.splitlines('hello\nhow are you')

array(list(['hello', 'how are you']), dtype=object)

In [279]:
np.char.strip('asdsa asd a','a')

array('sdsa asd ', dtype='<U11')

In [280]:
np.char.replace('she is bad girl','is','was')

array('she was bad girl', dtype='<U16')

In [281]:
np.char.replace('asdsa asd a','a','')

array('sds sd ', dtype='<U7')

In [282]:
np.char.join(':','asd')

array('a:s:d', dtype='<U5')

In [283]:
np.char.join([":","-"],['asd','dfg'])

array(['a:s:d', 'd-f-g'], dtype='<U5')

### 统计函数

In [285]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print(a)

[[3 7 5]
 [8 4 3]
 [2 4 9]]


In [287]:
np.min(a,axis=0)

array([2, 4, 3])

In [288]:
np.min(a,axis=1)

array([3, 3, 2])

In [289]:
np.max(a,axis=0)

array([8, 7, 9])

In [290]:
np.max(a,axis=1)

array([7, 8, 9])

In [291]:
np.ptp(a)

7

In [292]:
np.ptp(a,axis=0)

array([6, 3, 6])

In [293]:
np.ptp(a,axis=1)

array([4, 5, 7])

In [294]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [296]:
np.percentile(a,50,axis=0)

array([3., 4., 5.])

In [297]:
np.percentile(a,50,axis=1)

array([5., 4., 4.])

In [298]:
a = np.array([[20,30,10,40],[80,20,10,30]])
a

array([[20, 30, 10, 40],
       [80, 20, 10, 30]])

In [299]:
np.percentile(a,50,axis=1)

array([25., 25.])

In [300]:
np.percentile(a,75,axis=1)

array([32.5, 42.5])

Q1 = (n+1) *0.25

Q2 = (n+1) *0.5

Q3 = (n+1) *0.75

In [301]:
5*0.75

3.75

In [303]:
np.median(a,axis=1)

array([25., 25.])

In [304]:
np.mean(a,axis=0)

array([50., 25., 10., 35.])

In [306]:
a = np.array([1,2,3,4])
w = [4,3,2,1]
np.average(a,weights=w,returned=True)

(2.0, 10.0)

In [307]:
np.std([1,2,3,4])

1.118033988749895

sqrt(mean(x-x.mean())**2)

### 排序

In [309]:
a = np.array([[3,7],[9,1]])
a

array([[3, 7],
       [9, 1]])

In [310]:
a.shape

(2, 2)

In [311]:
np.sort(a)

array([[3, 7],
       [1, 9]])

In [312]:
np.sort(a,axis=0)

array([[3, 1],
       [9, 7]])

In [2]:
x = np.array([3,1,2])
x

array([3, 1, 2])

In [3]:
y = np.argsort(x)
y

array([1, 2, 0], dtype=int64)

In [4]:
x[y]

array([1, 2, 3])

In [13]:
a = [1,5,1,4,3,4,4]
b = [9,4,0,4,0,2,1]

In [14]:
ind = np.lexsort((b,a))

In [15]:
ind

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [ ]:
0 2 4 3 5 6 1 # a index

9 0 0 4 2 1 4 # b值
 
0 9 0 1 2 4 4 # 排序后的b值

In [9]:
[(a[i],b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

### 搜索函数

In [16]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [17]:
np.argmax(a)

7

In [20]:
a.flatten()[7]

90

In [21]:
np.argmax(a,axis=0)

array([1, 2, 0], dtype=int64)

In [22]:
np.argmax(a,axis=1)

array([2, 0, 1], dtype=int64)

In [23]:
a = np.array([[30,40,0],[0,20,10],[50,0,60]])
a

array([[30, 40,  0],
       [ 0, 20, 10],
       [50,  0, 60]])

In [24]:
np.nonzero(a)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 1, 2, 0, 2], dtype=int64))

In [26]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
np.where(x>3)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [28]:
x[np.where(x>3)]

array([4, 5, 6, 7, 8])

In [32]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
condition = np.mod(x,2)==0
print(condition)

[[ True False  True]
 [False  True False]
 [ True False  True]]


In [34]:
np.extract(condition,x)

array([0, 2, 4, 6, 8])

In [35]:
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
x.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [37]:
a =np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [38]:
a.T

array([0, 1, 2, 3, 4, 5, 6])

### 唯一化和集合逻辑

In [39]:
# 字符串去重
names = np.array(['Evan','Kid','Alice','Kid','Alice'])
names

array(['Evan', 'Kid', 'Alice', 'Kid', 'Alice'], dtype='<U5')

In [40]:
np.unique(names)

array(['Alice', 'Evan', 'Kid'], dtype='<U5')

In [42]:
# 整数去重
arr  = np.array([1,2,3,4,2,1,4,1,3])
len(np.unique(arr))

4

In [44]:
# 布尔值去重
bools = np.array([False,True,False,True])
np.unique(bools)

array([False,  True])

In [45]:
bools.any()

True

In [46]:
bools.all()

False

In [47]:
a = np.array([4,5,6,2,5,7,4,0])
b = np.array([1,2,3,4,7,8,4,3])

In [48]:
np.in1d(a,[5,7,0]) # 验证a中元素是否在给出的序列当中

array([False,  True, False, False,  True,  True, False,  True])

In [49]:
# 求交集
np.intersect1d(a,b)

array([2, 4, 7])

In [50]:
# 求并集
np.union1d(a,b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
# 求差集
np.setdiff1d(a,b)

array([0, 5, 6])

In [53]:
np.setdiff1d(b,a)

array([1, 3, 8])

### 矩阵库

In [54]:
import numpy.matlib

In [55]:
m = np.matlib.empty((2,2))
m

matrix([[4.24399158e-314, 8.48798317e-314],
        [1.06099790e-313, 1.48539705e-313]])

In [56]:
type(m)

numpy.matrixlib.defmatrix.matrix

In [57]:
np.matlib.zeros((2,2))

matrix([[0., 0.],
        [0., 0.]])

In [58]:
np.matlib.ones((2,2))

matrix([[1., 1.],
        [1., 1.]])

In [60]:
np.matlib.eye(n=3,M=4,k=1,dtype=float)

matrix([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [61]:
np.matlib.eye(3,4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [62]:
np.matlib.identity(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [63]:
np.matlib.rand(3,3)

matrix([[0.53712362, 0.97709798, 0.19467271],
        [0.15639653, 0.56287767, 0.32159322],
        [0.58194965, 0.72308414, 0.15881701]])

In [64]:
i = np.matrix('1,2;3,4')
i

matrix([[1, 2],
        [3, 4]])

In [66]:
np.matrix([['1','2'],[3,4]])

matrix([['1', '2'],
        ['3', '4']], dtype='<U1')

In [69]:
j = np.asarray(i)  #矩阵转数组

In [70]:
type(j)

numpy.ndarray

In [71]:
np.mat(j)   # 数组转矩阵

matrix([[1, 2],
        [3, 4]])

### 线性代数

In [72]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


In [73]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [74]:
a @ b

array([[37, 40],
       [85, 92]])

In [75]:
np.vdot(a,b)

130

In [76]:
a = np.array([1,2,3,4])
b = np.array([11,12,13,14]).reshape(4,1)
print(a)
print(b)

[1 2 3 4]
[[11]
 [12]
 [13]
 [14]]


In [77]:
np.vdot(a,b)

130

In [78]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


In [79]:
np.inner(a,b)

array([[35, 41],
       [81, 95]])

1*11+2*12, 1*13+2*14
3*11+4*12, 3*13+4*14

In [80]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [81]:
np.matmul(a,b)

array([[37, 40],
       [85, 92]])

#### 行列式

In [82]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [83]:
np.linalg.det(a)

-2.0000000000000004

In [84]:
b = np.array([[6,1,1],[4,-2,5],[2,8,7]])
b

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [85]:
np.linalg.det(b)

-306.0

In [86]:
6*-2*7 + 4*8*1 + 1*5*2 - (1*-2*2 + 1* 4* 7 + 5* 8* 6)

-306

#### 线性方程组的解

x+y+z=6

2y+5z=-4

2x+5y-z=27

In [87]:
A = np.array([[1,1,1],[0,2,5],[2,5,-1]])
B = np.array([6,-4,27])
print(A)
print(B)

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
[ 6 -4 27]


In [89]:
X = np.linalg.solve(A,B)
X

array([ 5.,  3., -2.])

In [90]:
np.dot(A,X)

array([ 6., -4., 27.])

In [91]:
a = np.array([[1,2],[3,4]])
b = np.linalg.inv(a)
print(a)
print(b)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [93]:
a.dot(b)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])